# ============================================================
# Banking Service - Centralized Configuration
# ============================================================
# Served by Config Server at http://localhost:8888
# ============================================================

server:
  port: ${SERVER_PORT:8081}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# ============================================================
# Eureka Client
# ============================================================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port:8081}

# ============================================================
# JWT Configuration
# ============================================================
jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# ============================================================
# CORS Configuration
# ============================================================
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8080}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true

# ============================================================
# Logging
# ============================================================
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.RRBank: DEBUG
